Build docs prior to deploy
Signed-off-by: Kurt Greaves <kurt.greaves@zepben.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -31,10 +31,65 @@ jobs:
           LC_URL: ${{ secrets.LC_URL }}
           PATH: src
 
+  build-docs:
+    needs: release-checks
+    runs-on: ubuntu-latest
+    outputs:
+      artifact: docs
+    container: node:12-alpine
+    steps:
+      - name: Install Git
+        run: |
+          apk add git
+
+      - name: Work around git permission issue
+        run: |
+          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
+          git config --global --add safe.directory /__w/$dname/$dname
+        shell: sh
+
+      - uses: actions/checkout@v2
+
+      - name: Checkout release branch
+        run: |
+          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+          git fetch --all
+          git checkout release
+        shell: bash
+
+      - name: Cache nodejs deps
+        uses: actions/cache@v2
+        with:
+          path: ~/.npm
+          key: npm
+
+      - name: Build docusaurus
+        id: build
+        uses: zepben/docusaurus-action@main
+        with:
+          VERSION: ${{ needs.deploy.outputs.version }}
+          NPM_REPO: ${{ secrets.NPM_REPO }}
+          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+        continue-on-error: true
+
+      - uses: actions/upload-artifact@master
+        if: steps.build.outcome == 'success'
+        with:
+          name: docs
+          path: docs/build/
+
+      - name: Fail build
+        if: steps.build.outcome == 'failure'
+        run: | 
+          git push origin -d release
+          echo "There was an error in the docusaurus build above."
+          exit 1
+        shell: sh
+
   deploy:
     runs-on: ubuntu-latest
     container: python:3.7
-    needs: release-checks
+    needs: build-docs
     outputs:
       artifact: ${{ steps.build.outputs.artifact }}
       version: ${{ steps.build.outputs.version }}
@@ -50,13 +105,6 @@ jobs:
         shell: bash
 
       - uses: actions/checkout@v2
-
-      - name: Checkout release branch
-        run: |
-          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
-          git fetch --all
-          git checkout release
-        shell: bash
 
       - name: Build and publish
         id: build
@@ -92,54 +140,6 @@ jobs:
           echo "There was an error in the python build and publish commands above."
           exit 1
         shell: bash
-
-  build-docs:
-    needs: [deploy]
-    runs-on: ubuntu-latest
-    outputs:
-      artifact: docs
-    container: node:12-alpine
-    steps:
-      - name: Install Git
-        run: |
-          apk add git
-
-      - name: Work around git permission issue
-        run: |
-          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
-          git config --global --add safe.directory /__w/$dname/$dname
-        shell: sh
-
-      - uses: actions/checkout@v2
-
-      - name: Cache nodejs deps
-        uses: actions/cache@v2
-        with:
-          path: ~/.npm
-          key: npm
-
-      - name: Build docusaurus
-        id: build
-        uses: zepben/docusaurus-action@main
-        with:
-          VERSION: ${{ needs.deploy.outputs.version }}
-          NPM_REPO: ${{ secrets.NPM_REPO }}
-          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
-        continue-on-error: true
-
-      - uses: actions/upload-artifact@master
-        if: steps.build.outcome == 'success'
-        with:
-          name: docs
-          path: docs/build/
-
-      - name: Fail build
-        if: steps.build.outcome == 'failure'
-        run: | 
-          git push origin -d release
-          echo "There was an error in the docusaurus build above."
-          exit 1
-        shell: sh
 
   create-release:
     needs: [deploy, build-docs]
